# Generated by Django 3.0.8 on 2022-06-18 20:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_cliente_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='created_at',
        ),
        migrations.AddField(
            model_name='cliente',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 18, 17, 51, 7, 600989)),
        ),
    ]
