# Generated by Django 4.0.5 on 2022-06-19 20:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_alter_cliente_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 19, 17, 16, 10, 959174)),
        ),
    ]
